import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'FR' | 'EN';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  FR: {
    'nav.method': 'Méthode',
    'nav.philosophy': 'Philosophie',
    'nav.talents': 'Talents',
    'nav.offers': 'Offres',
    'nav.contact': 'Contact',
    'nav.cta': 'Démarrer un projet',
    'hero.title1': 'Marketing Digital :',
    'hero.title2': "Passez de l'ombre à la lumière.",
    'hero.subtitle':
      "L'agence qui combine l'agilité des meilleurs créatifs freelances à la rigueur d'une stratégie Data-Driven.",
    'hero.cta.primary': 'Démarrer un projet',
    'hero.cta.secondary': 'Voir nos talents',
    'vision.title': 'Soyez LUCID sur votre stratégie.',
    'vision.body':
      "Le marché est bruyant. Pour vous faire entendre, vous n'avez pas besoin de crier plus fort — vous avez besoin de voir plus clair. Chez LUCID, nous ne vendons pas du 'joli', nous vendons du rentable. Nous analysons vos données pour piloter nos experts créatifs.",
    'vision.stat1.val': '3x',
    'vision.stat1.label': 'ROI moyen constaté',
    'vision.stat2.val': '48h',
    'vision.stat2.label': 'Délai de démarrage',
    'vision.stat3.val': '100%',
    'vision.stat3.label': 'Projets livrés clé en main',
    'method.title': 'Notre Méthode',
    'method.step1.title': 'ANALYSE',
    'method.step1.body': 'Nous auditons votre marché et vos chiffres avant de bouger.',
    'method.step2.title': 'CASTING',
    'method.step2.body': "Nous sélectionnons dans notre réseau l'expert parfait pour VOTRE besoin.",
    'method.step3.title': 'PILOTAGE',
    'method.step3.body': 'Nous gérons la production de A à Z. Vous recevez un projet clé en main.',
    'talents.title': "L'élite des créatifs. Pilotée par nos experts.",
    'talents.cta': "Réserver ce talent via l'Agence",
    'talents.filter.all': 'Tous',
    'talents.filter.branding': 'Branding',
    'talents.filter.video': 'Vidéo',
    'talents.filter.web': 'Web',
    'talents.filter.photo': 'Photo',
    'talents.more': 'Voir plus',
    'offers.title': 'Nos Solutions sur Mesure',
    'offers.included': "Inclus dans l'offre",
    'offers.audit.name': 'DIAGNOSTIC',
    'offers.audit.type': 'Audit Stratégique',
    'offers.audit.features':
      'Audit de visibilité · Analyse de la concurrence · Roadmap stratégique',
    'offers.audit.included': 'Présentation détaillée & Recommandations',
    'offers.audit.cta': 'Réserver mon audit',
    'offers.production.name': 'SOLUTIONS',
    'offers.production.type': 'Production Créative',
    'offers.production.features':
      'Identité visuelle · Développement Web · Contenus Social Media · Publicité (Ads)',
    'offers.production.included': 'Casting experts + Pilotage de projet',
    'offers.production.cta': 'Lancer une production',
    'offers.growth.name': 'PARTENAIRE',
    'offers.growth.type': 'Accompagnement Croissance',
    'offers.growth.features':
      'Pilotage Data-Driven · Création continue · Optimisation du ROI · Support prioritaire',
    'offers.growth.included': 'Accès direct aux experts + Reporting Live',
    'offers.growth.badge': 'Le plus populaire',
    'offers.growth.cta': 'Devenir partenaire',
    'results.roi': 'ROI moyen client',
    'results.reach': 'Personnes touchées',
    'results.conversion': 'Taux de satisfaction',
    'testimonials.1':
      '"LUCID a transformé notre présence digitale en moins de 3 mois. Le ROI dépasse toutes nos attentes."',
    'testimonials.2':
      '"Une équipe de talents exceptionnels, pilotée avec une rigueur impressionnante. Je recommande sans réserve."',
    'testimonials.1.author': 'Jean Dupont',
    'testimonials.1.role': 'CEO, TechFlow',
    'testimonials.2.author': 'Marie Laurent',
    'testimonials.2.role': 'Marketing Director, LuxeStyle',
    'footer.legal': 'Mentions légales',
    'footer.privacy': 'Politique de confidentialité',
    'back.to.top': 'Retour en haut',
    'results.title': 'Des résultats mesurables.',
    'results.subtitle': 'Nous ne choisissons pas les likes, nous choisissons les ventes.',
    'contact.title': 'Démarrons votre projet.',
    'contact.reassurance': 'Réponse sous 24h — Premier audit offert.',
    'contact.name': 'Nom complet',
    'contact.company': 'Entreprise',
    'contact.type': 'Type de projet',
    'contact.budget': 'Budget',
    'contact.budget.details': 'Precisez votre budget',
    'contact.budget.details.placeholder': 'Ex : 750 000 FCFA',
    'contact.message': 'Message (requis)',
    'contact.submit': 'Envoyer ma demande',
    'footer.tagline': 'Propulsé par la Data. Sublimé par le Talent.',
    'footer.join': 'Espace Freelances',
    'join.title': 'Rejoindre le collectif LUCID.',
    'join.subtitle': 'Fini la prospection. Concentrez-vous sur la création.',
    'join.benefit1': 'Missions régulières. Revenus stables.',
    'join.benefit2': 'Structure professionnelle. Visibilité maîtrisée.',
    'join.benefit3': 'Accédez à des projets premium sélectionnés.',
    'join.cta': 'Soumettre ma candidature',
    'philosophy.vision.title': 'Notre Vision',
    'philosophy.vision.subtitle':
      'Faire de chaque PME africaine une entreprise qui performe digitalement.',
    'philosophy.vision.body':
      'Nous croyons qu’une petite entreprise bien accompagnée peut rivaliser avec n’importe quel acteur de son marché. Le digital est ce levier. Nous sommes l’architecte qui le construit. En Afrique de l’Ouest, le talent existe, la demande existe, le potentiel est immense. Ce qui manque, c’est une structure capable de relier la bonne stratégie, les bons créatifs et les bons outils — au bon moment, pour le bon budget. LUCID Agency est née pour combler ce vide.',
    'philosophy.mission.title': 'Notre Mission',
    'philosophy.mission.subtitle':
      'Transformer votre présence digitale en moteur de croissance réelle.',
    'philosophy.mission.body1':
      'Nous ne vendons pas de la visibilité. Nous construisons des systèmes de communication pilotés par la donnée, exécutés par des talents soigneusement sélectionnés, et mesurés à l’aune d’un seul critère : vos résultats.',
    'philosophy.mission.body2':
      'Pour les PME et startups, nous sommes votre département marketing externalisé — stratégique, agile, et accessible.',
    'philosophy.mission.body3':
      'Pour les freelances créatifs, nous sommes la structure qui valorise votre talent et stabilise vos revenus.',
    'philosophy.values.title': 'Nos Valeurs',
    'philosophy.values.subtitle': 'Ce qui nous guide chaque jour.',
    'philosophy.values.1.title': '01 — La donnée avant tout',
    'philosophy.values.1.body':
      'Aucune création sans analyse. Chaque décision est fondée sur des données réelles, pas sur des intuitions.',
    'philosophy.values.2.title': '02 — L’excellence des talents',
    'philosophy.values.2.body':
      'Nous sélectionnons uniquement les créatifs qui correspondent précisément au projet. Qualité et pertinence, pas volume.',
    'philosophy.values.3.title': '03 — Des résultats mesurables',
    'philosophy.values.3.body':
      'Likes ou ventes — nous choisissons les ventes. Chaque action est tracée, analysée et optimisée pour votre croissance.',
    'philosophy.values.4.title': '04 — La transparence totale',
    'philosophy.values.4.body':
      'Vous savez ce qui est fait, pourquoi c’est fait, et ce que ça produit. Aucune boîte noire, aucune surprise.',
    'dashboard.nav.overview': 'Tableau de bord',
    'dashboard.nav.missions': 'Missions',
    'dashboard.nav.messages': 'Messages',
    'dashboard.nav.settings': 'Paramètres',
    'dashboard.nav.logout': 'Déconnexion',
    'dashboard.welcome': 'Bonjour, {{name}} 👋',
    'dashboard.welcome.sub': "Voici ce qui se passe sur votre espace aujourd'hui.",
    'dashboard.stats.activeMissions': 'Missions en cours',
    'dashboard.stats.missions': 'Missions disponibles',
    'dashboard.stats.applications': 'Candidatures',
    'dashboard.stats.revenue': 'Revenus ce mois',
    'dashboard.stats.profile': 'Profil complété',
    'dashboard.nav.contracts': 'Mes Contrats',
    'dashboard.nav.applications': 'Mes Candidatures',
    'dashboard.nav.saved': 'Enregistrés',
    'dashboard.settings.security.change': 'Changer le mot de passe',
    'dashboard.settings.security.current': 'Mot de passe actuel',
    'dashboard.settings.security.new': 'Nouveau mot de passe',
    'dashboard.settings.security.confirm': 'Confirmer le nouveau mot de passe',
    'dashboard.settings.security.submit': 'Mettre à jour le mot de passe',
    'admin.nav.projects.new': 'Nouveau Projet',
    'admin.settings.agency.title': 'Infos Agence',
    'admin.settings.security.title': 'Sécurité',
    'admin.projects.table.project': 'Projet',
    'admin.projects.table.client': 'Client',
    'admin.projects.table.talent': 'Talent',
    'admin.projects.table.budget': 'Budget',
    'admin.projects.table.status': 'Statut',
    'admin.projects.status.inprogress': 'En cours',
    'admin.projects.status.completed': 'Terminé',
    'admin.projects.status.onhold': 'En pause',
    'dashboard.missions.title': 'Missions recommandées',
    'dashboard.missions.search': 'Rechercher une mission...',
    'dashboard.missions.view': "Voir l'offre",
    'dashboard.messages.title': 'Vos conversations',
    'dashboard.messages.empty': 'Aucun message pour le moment.',
    'dashboard.settings.title': 'Paramètres du compte',
    'dashboard.settings.profile': 'Profil Public',
    'dashboard.settings.notifications': 'Notifications',
    'dashboard.settings.security': 'Sécurité',
    'admin.nav.talents': 'Gestion Talents',
    'admin.nav.clients': 'Clients',
    'admin.nav.projects': 'Projets Clients',
    'admin.nav.messages': 'Messagerie',
    'admin.nav.settings': 'Paramètres',
    'admin.welcome': 'Back-office Admin 🛠️',
    'admin.welcome.sub': 'Gérez vos talents et vos projets clients en toute simplicité.',
    'admin.stats.activeTalents': 'Talents Actifs',
    'admin.stats.clients': 'Contacts clients',
    'admin.stats.activeProjects': 'Projets en cours',
    'admin.stats.pendingRequests': 'Demandes en attente',
    'admin.talents.title': 'Dernières demandes de talents',
    'admin.talents.table.talent': 'Talent',
    'admin.talents.table.specialty': 'Spécialité',
    'admin.talents.table.date': 'Date',
    'admin.talents.table.status': 'Statut',
    'admin.talents.table.actions': 'Actions',
    'admin.status.approved': 'Approuvé',
    'admin.status.pending': 'En attente',
    'admin.status.rejected': 'Refusé',
    'login.title.admin': 'Accès Admin',
    'login.title.freelancer': 'Espace Freelance',
    'login.subtitle': 'Veuillez vous connecter pour accéder à votre espace.',
    'login.label.username': 'Pseudo',
    'login.label.email': 'Email',
    'login.label.password': 'Mot de passe',
    'login.placeholder.username': 'Votre pseudo',
    'login.placeholder.password': '••••••••',
    'login.emailPlaceholder': 'votre@email.com',
    'login.passwordPlaceholder': '••••••••',
    'login.button': 'Se connecter',
    'login.button.admin': 'Accéder à l’admin',
    'login.error': 'Identifiants incorrects. Veuillez réessayer.',
    'login.error.missingFields': 'Veuillez renseigner votre email et votre mot de passe.',
    'login.error.invalidEmail': 'Veuillez entrer une adresse email valide.',
    'login.error.rateLimit': 'Trop de tentatives. Réessayez dans {{seconds}} secondes.',
    'login.error.adminAccess': "Ce compte n'a pas accès à l'administration.",
    'login.error.noFreelancer': 'Aucune candidature freelancer associée à ce compte.',
    'login.error.pending': 'Votre candidature est en attente de validation.',
    'login.error.rejected': 'Votre candidature a été rejetée.',
    'login.error.suspended': 'Votre compte est suspendu.',
    'login.error.invalidCredentials': 'Email ou mot de passe incorrect.',
    'login.error.emailNotConfirmed': 'Veuillez confirmer votre email avant de vous connecter.',
    'login.error.profileMissing': 'Compte incomplet. Contactez un administrateur.',
    'login.error.generic': 'Une erreur est survenue. Veuillez réessayer.',
    'login.togglePassword': 'Afficher ou masquer le mot de passe',
    'login.submitLoading': 'Connexion...',
    'login.registerPrompt': "Vous n'avez pas de compte ?",
    'login.registerLink': "S'inscrire",
    'login.reset.link': 'Mot de passe oublié ?',
    'login.reset.title': 'Mot de passe oublié ?',
    'login.reset.subtitle':
      'Entrez votre email et nous vous enverrons un lien de réinitialisation.',
    'login.reset.submit': 'Envoyer le lien',
    'login.reset.submitLoading': 'Envoi...',
    'login.reset.back': 'Retour à la connexion',
    'login.reset.success.title': 'Email envoyé !',
    'login.reset.success.body':
      'Vérifiez votre boîte mail et cliquez sur le lien pour réinitialiser votre mot de passe.',
    'login.reset.error.missingEmail': 'Veuillez renseigner votre email.',
    'login.reset.error.invalidEmail': 'Veuillez entrer une adresse email valide.',
    'login.reset.error.sendFailed': "Impossible d'envoyer le lien. Vérifiez l'email.",
    'resetPassword.loading.title': 'Vérification du lien',
    'resetPassword.loading.body': 'Nous préparons votre session de réinitialisation.',
    'resetPassword.title': 'Réinitialiser le mot de passe',
    'resetPassword.subtitle':
      'Choisissez un nouveau mot de passe en respectant exactement les mêmes règles de sécurité que lors de votre inscription.',
    'resetPassword.submit': 'Réinitialiser le mot de passe',
    'resetPassword.submitLoading': 'Réinitialisation...',
    'resetPassword.success.title': 'Mot de passe mis à jour',
    'resetPassword.success.body':
      'Votre mot de passe a bien été réinitialisé. Redirection vers la connexion...',
    'resetPassword.invalid.title': 'Lien invalide ou expiré',
    'resetPassword.invalid.cta': 'Retour à la connexion',
    'resetPassword.error.invalidLink':
      'Ce lien de réinitialisation est invalide, incomplet ou expiré.',
    'resetPassword.error.missingRecoverySession':
      'La session de réinitialisation est absente. Veuillez redemander un nouveau lien.',
    'resetPassword.error.generic': 'Impossible de réinitialiser le mot de passe pour le moment.',
    'dashboard.nav.history': 'Historique des missions',
    'dashboard.stats.available': 'Missions disponibles',
    'dashboard.stats.accepted': 'Missions acceptées',
    'dashboard.stats.completed': 'Missions terminées',
    'dashboard.profile.fallbackName': 'Freelancer',
    'dashboard.overview.details': 'Voir les détails',
    'dashboard.overview.summaryTitle': 'Aperçu',
    'dashboard.overview.summaryBody':
      'Vos missions apparaîtront ici dès qu’elles vous seront assignées.',
    'dashboard.missions.emptyTitle': 'Aucune mission disponible',
    'dashboard.missions.emptyBody':
      'Aucune mission n’est disponible pour le moment. Revenez plus tard.',
    'dashboard.history.emptyTitle': 'Historique vide',
    'dashboard.history.emptyBody':
      'Aucune mission acceptée ou terminée n’est encore disponible sur votre compte.',
    'dashboard.history.action': 'Voir les missions',
    'dashboard.messages.emptyTitle': 'Vos conversations',
    'dashboard.messages.emptyBody': 'Aucun message pour le moment.',
    'dashboard.settings.card.profileDesc': 'Gérez vos informations visibles par l’agence.',
    'dashboard.settings.card.notificationsDesc': 'Configurez vos préférences de notification.',
    'dashboard.settings.card.securityDesc': 'Mettez à jour votre mot de passe.',
    'dashboard.settings.profile.firstName': 'Prénom',
    'dashboard.settings.profile.lastName': 'Nom',
    'dashboard.settings.profile.phone': 'Téléphone',
    'dashboard.settings.profile.phonePlaceholder': '+228 XX XX XX XX',
    'dashboard.settings.profile.portfolio': 'Portfolio',
    'dashboard.settings.profile.portfolioPlaceholder': 'https://monportfolio.com',
    'dashboard.settings.profile.bio': 'Bio',
    'dashboard.settings.profile.bioPlaceholder': 'Décrivez votre profil et votre expertise...',
    'dashboard.settings.profile.save': 'Enregistrer',
    'dashboard.settings.profile.saving': 'Sauvegarde...',
    'dashboard.settings.profile.success': 'Profil mis à jour.',
    'dashboard.settings.profile.error': 'Impossible de mettre à jour le profil.',
    'dashboard.settings.security.placeholder': 'Min. 8 caractères',
    'dashboard.settings.security.confirmPlaceholder': 'Confirmez le mot de passe',
    'dashboard.settings.security.success': 'Mot de passe mis à jour.',
    'dashboard.settings.security.saving': 'Mise à jour...',
    'dashboard.settings.security.error': 'Impossible de mettre à jour le mot de passe.',
    'dashboard.settings.security.errorMismatch': 'Les mots de passe ne correspondent pas.',
    'dashboard.settings.security.errorInvalid': 'Mot de passe invalide : {{errors}}.',
    'dashboard.settings.notifications.missions': 'Nouvelles missions disponibles',
    'dashboard.settings.notifications.history': 'Mises à jour de mon historique',
    'dashboard.settings.notifications.messages': "Messages de l'agence",
    'dashboard.settings.notifications.newsletter': 'Newsletter mensuelle',
    'dashboard.settings.notifications.save': 'Enregistrer',
    'admin.common.na': 'N/A',
    'admin.error.invalidSession': 'Session admin invalide.',
    'admin.error.loadTalents': 'Impossible de charger les candidatures.',
    'admin.error.loadContacts': 'Impossible de charger les contacts.',
    'admin.error.updateStatus': 'Impossible de mettre à jour le statut.',
    'admin.search.placeholder': 'Rechercher...',
    'admin.filter.all': 'Tous',
    'admin.filter.pending': 'En attente',
    'admin.filter.validated': 'Validés',
    'admin.filter.rejected': 'Refusés',
    'admin.filter.suspended': 'Suspendus',
    'admin.talents.empty.none': 'Aucune candidature reçue pour le moment.',
    'admin.talents.empty.filtered': 'Aucun résultat.',
    'admin.talents.table.phone': 'Téléphone',
    'admin.talents.table.dayRate': 'Tarif jour',
    'admin.talents.table.onboarding': 'Onboarding',
    'admin.onboarding.complete': 'Complet',
    'admin.onboarding.incomplete': 'Incomplet',
    'admin.status.suspended': 'Suspendu',
    'admin.clients.title': 'Contacts clients',
    'admin.clients.empty.none': 'Aucun contact reçu pour le moment.',
    'admin.clients.empty.filtered': 'Aucun contact ne correspond à votre recherche.',
    'admin.clients.table.name': 'Nom',
    'admin.clients.table.company': 'Entreprise',
    'admin.clients.table.email': 'Email',
    'admin.clients.table.phone': 'Téléphone',
    'admin.clients.table.projectType': 'Type de projet',
    'admin.clients.table.budget': 'Budget',
    'admin.clients.table.date': 'Date',
    'admin.clients.table.actions': 'Actions',
    'admin.clients.actions.viewDetails': 'Voir détails',
    'admin.clients.modal.title': 'Détail du client',
    'admin.clients.modal.firstName': 'Prénom',
    'admin.clients.modal.message': 'Message',
    'admin.clients.modal.status': 'Statut',
    'admin.pagination.rowsPerPage': 'Lignes par page',
    'admin.pagination.results': 'résultats',
    'admin.pagination.of': 'sur',
    'admin.pagination.page': 'Page',
    'admin.pagination.on': 'sur',
    'admin.pagination.previous': 'Précédent',
    'admin.pagination.next': 'Suivant',
    'admin.pagination.noResults': '0 résultat',
    'admin.projects.emptyTitle': 'Aucun projet disponible',
    'admin.projects.emptyBody': 'Aucune donnée projet réelle n’est encore fournie par le backend.',
    'admin.messages.title': 'Messagerie WhatsApp',
    'admin.messages.subtitle': 'Contactez directement vos talents validés.',
    'admin.messages.empty': 'Aucun talent approuvé.',
    'admin.messages.openWhatsapp': 'Ouvrir WhatsApp',
    'admin.messages.noPhone': 'Téléphone indisponible',
    'admin.settings.security.label': 'Sécurité',
    'admin.settings.security.desc': 'Mot de passe et accès administrateur.',
    'admin.settings.security.newLabel': 'Nouveau mot de passe',
    'admin.settings.security.newPlaceholder': 'Min. 8 caractères',
    'admin.settings.security.confirmLabel': 'Confirmer',
    'admin.settings.security.confirmPlaceholder': 'Répétez le mot de passe',
    'admin.settings.security.toggleVisibility': 'Afficher ou masquer le mot de passe',
    'admin.settings.security.submit': 'Mettre à jour',
    'admin.settings.security.saving': 'Mise à jour...',
    'admin.settings.security.success': 'Mot de passe mis à jour.',
    'admin.settings.security.error': 'Impossible de mettre à jour le mot de passe.',
    'admin.settings.security.errorMismatch': 'Les mots de passe ne correspondent pas.',
    'admin.settings.security.errorMin': 'Minimum 8 caractères.',
    'admin.settings.security.errorInvalid': 'Mot de passe invalide : {{errors}}.',
    'admin.settings.system.label': 'Paramètres système',
    'admin.settings.system.desc': 'Vue synthétique des données chargées.',
    'admin.settings.system.totalTalents': 'Talents inscrits',
    'admin.settings.system.validatedTalents': 'Talents validés',
    'admin.settings.system.pendingTalents': 'En attente',
    'admin.settings.back': 'Retour',
    'admin.actions.processing': 'Traitement...',
    'admin.actions.approve': 'Approuver',
    'admin.actions.reject': 'Refuser',
    'admin.reject.reasonLabel': 'Motif du refus',
    'admin.reject.reasonPlaceholder': 'Expliquez brièvement pourquoi la candidature est refusée.',
    'admin.reject.reasonRequired': 'Le motif du refus est obligatoire.',
    'admin.reject.confirm': 'Confirmer le refus',
    'admin.modal.validated': 'Validé',
    'admin.modal.suspended': 'Suspendu',
    'admin.modal.rejected': 'Refusé',
    'completeProfile.title': 'Compléter votre profil',
    'completeProfile.subtitle':
      'Pour accéder au tableau de bord, renseignez les informations suivantes.',
    'completeProfile.field.phone': 'Numéro de téléphone',
    'completeProfile.field.phonePlaceholder': '+221770000000',
    'completeProfile.field.rate': 'Tarif journalier (FCFA)',
    'completeProfile.field.rateSuffix': '/jour',
    'completeProfile.field.bio': 'Bio (optionnel)',
    'completeProfile.field.bioPlaceholder': 'Parlez-nous de vous et de votre expérience...',
    'completeProfile.field.speciality': 'Spécialité (optionnel)',
    'completeProfile.field.specialityPlaceholder': 'Ex: Développeur React, Vidéaste...',
    'completeProfile.submit.idle': 'Compléter mon profil',
    'completeProfile.submit.loading': 'Enregistrement...',
    'completeProfile.loading.title': 'Chargement du profil',
    'completeProfile.loading.body': 'Nous préparons votre espace freelancer.',
    'completeProfile.pending.title': 'Préparation de votre profil',
    'completeProfile.pending.body':
      'Vos informations freelancer sont en cours de chargement. Réessayez dans un instant.',
    'completeProfile.fallback.title': 'Session requise',
    'completeProfile.fallback.body': 'Reconnectez-vous pour terminer votre onboarding.',
    'completeProfile.success.title': 'Profil terminé !',
    'completeProfile.success.body': 'Redirection vers le tableau de bord...',
    'completeProfile.error.phoneRequired': 'Numéro de téléphone requis',
    'completeProfile.error.phoneInvalid': 'Format invalide : +COUNTRYCODE suivi de 8 à 15 chiffres',
    'completeProfile.error.rateInvalid': 'Le tarif doit être compris entre 1000 et 1000000 FCFA.',
    'completeProfile.error.noSession': 'Session invalide.',
    'completeProfile.error.submit': 'Impossible de compléter le profil.',
    'join.specialty.graphisme': 'Designer graphique',
    'join.specialty.video': 'Vidéaste / Monteur vidéo',
    'join.specialty.redaction': 'Rédacteur / Copywriter',
    'join.specialty.webdev': 'Développeur web',
    'join.specialty.photo': 'Photographe',
    'join.specialty.marketing': 'Spécialiste marketing digital',
    'join.specialty.autre': 'Autre expertise',
    'join.success.title': 'Candidature envoyée !',
    'join.success.body1': 'Votre candidature a bien été reçue.',
    'join.success.body2': "Notre équipe l'examinera et vous recontactera.",
    'join.field.firstName': 'Prénom',
    'join.field.lastName': 'Nom',
    'join.field.email': 'Email',
    'join.field.phone': 'Numéro de téléphone',
    'join.field.rate': 'Tarif journalier (FCFA)',
    'join.field.rateSuffix': '/jour',
    'join.field.password': 'Mot de passe',
    'join.field.confirmPassword': 'Confirmer',
    'join.field.specialty': 'Spécialité',
    'join.field.portfolio': 'Lien portfolio',
    'join.field.message': 'Message (requis)',
    'join.placeholder.firstName': 'Ex: Jean',
    'join.placeholder.lastName': 'Ex: Dupont',
    'join.placeholder.email': 'Ex: jean@email.com',
    'join.placeholder.phone': '+221770000000',
    'join.placeholder.password': 'Min. 8 caractères',
    'join.placeholder.confirmPassword': 'Répétez votre mot de passe',
    'join.placeholder.specialty': 'Choisir votre spécialité',
    'join.placeholder.portfolio': 'https://monportfolio.com',
    'join.placeholder.message': 'Parlez-nous de vous et de votre expérience...',
    'join.help.phone': 'Format : +countrycode suivi de 8 à 15 chiffres',
    'join.help.rate': 'Min : 1000 FCFA | Max : 1,000,000 FCFA',
    'join.password.show': 'Voir',
    'join.password.hide': 'Cacher',
    'join.submit.loading': 'Envoi en cours...',
    'join.loginPrompt': 'Vous avez déjà un compte ?',
    'join.loginLink': 'Se connecter',
    'join.legal.prefix': "J'accepte les",
    'join.legal.link': "Conditions d'utilisation",
    'join.legal.error': "Vous devez accepter les conditions d'utilisation.",
    'join.error.generic': 'Une erreur est survenue. Veuillez réessayer.',
    'join.error.emailInUse': 'Cet email est déjà utilisé.',
    'join.error.rateLimit': 'Trop de tentatives. Réessayez dans {{minutes}} minutes.',
    'validation.min2': 'Minimum 2 caractères',
    'validation.max50': 'Maximum 50 caractères',
    'validation.invalidCharacters': 'Caractères invalides',
    'validation.invalidEmail': 'Email invalide',
    'validation.passwordMin': 'Minimum 8 caractères',
    'validation.passwordUppercase': 'Au moins une majuscule',
    'validation.passwordDigit': 'Au moins un chiffre',
    'validation.passwordSpecial': 'Au moins un caractère spécial',
    'validation.phoneRequired': 'Numéro de téléphone requis',
    'validation.phoneFormat': 'Format : +COUNTRYCODE suivi de 8 à 15 chiffres',
    'validation.rateMin': 'Minimum 1000 FCFA',
    'validation.rateMax': 'Maximum 1000000 FCFA',
    'validation.specialtyRequired': 'Veuillez choisir une spécialité',
    'validation.specialtyInvalid': 'Spécialité invalide',
    'validation.invalidUrl': 'URL invalide (ex: https://monportfolio.com)',
    'validation.max1000': 'Maximum 1000 caractères',
    'validation.noHtml': "Le HTML n'est pas autorisé",
    'validation.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'login.back': "Retour à l'accueil",
    'common.cancel': 'Annuler',
    'common.close': 'Fermer',
    'common.menu': 'Menu',
    'common.sessionCheck': 'Vérification de la session...',
    'common.redirecting': 'Redirection en cours...',
    'common.clickToReveal': 'Cliquez pour découvrir...',
  },
  EN: {
    'nav.method': 'Method',
    'nav.philosophy': 'Philosophy',
    'nav.talents': 'Talents',
    'nav.offers': 'Offers',
    'nav.contact': 'Contact',
    'nav.cta': 'Start a project',
    'hero.title1': 'Digital Marketing:',
    'hero.title2': 'Step out of the shadows.',
    'hero.subtitle':
      'The agency that combines the agility of top freelance creatives with the rigor of a Data-Driven strategy.',
    'hero.cta.primary': 'Start a project',
    'hero.cta.secondary': 'Meet our talents',
    'vision.title': 'Be LUCID about your strategy.',
    'vision.body':
      "The market is noisy. To be heard, you don't need to shout louder — you need to see clearer. At LUCID, we don't sell 'pretty', we sell profitable. We analyze your data to drive our creative experts.",
    'vision.stat1.val': '3x',
    'vision.stat1.label': 'Average measured ROI',
    'vision.stat2.val': '48h',
    'vision.stat2.label': 'Time to launch',
    'vision.stat3.val': '100%',
    'vision.stat3.label': 'Projects delivered end-to-end',
    'method.title': 'Our Method',
    'method.step1.title': 'ANALYSIS',
    'method.step1.body': 'We audit your market and numbers before making any move.',
    'method.step2.title': 'CASTING',
    'method.step2.body': 'We select from our network the perfect expert for YOUR need.',
    'method.step3.title': 'MANAGEMENT',
    'method.step3.body': 'We handle production from A to Z. You receive a ready-to-use project.',
    'talents.title': 'The creative elite. Driven by our experts.',
    'talents.cta': 'Book this talent via the Agency',
    'talents.filter.all': 'All',
    'talents.filter.branding': 'Branding',
    'talents.filter.video': 'Video',
    'talents.filter.web': 'Web',
    'talents.filter.photo': 'Photo',
    'talents.more': 'View more',
    'offers.title': 'Tailored Solutions',
    'offers.included': 'Included in the offer',
    'offers.audit.name': 'DIAGNOSIS',
    'offers.audit.type': 'Strategic Audit',
    'offers.audit.features': 'Visibility audit · Competitor analysis · Strategic roadmap',
    'offers.audit.included': 'Detailed presentation & Recommendations',
    'offers.audit.cta': 'Book my audit',
    'offers.production.name': 'SOLUTIONS',
    'offers.production.type': 'Creative Production',
    'offers.production.features':
      'Visual identity · Web development · Social Media content · Advertising (Ads)',
    'offers.production.included': 'Expert casting + Project management',
    'offers.production.cta': 'Start a production',
    'offers.growth.name': 'PARTNER',
    'offers.growth.type': 'Growth Partnership',
    'offers.growth.features':
      'Data-Driven steering · Continuous creation · ROI optimization · Priority support',
    'offers.growth.included': 'Direct expert access + Live reporting',
    'offers.growth.badge': 'Most popular',
    'offers.growth.cta': 'Become a partner',
    'results.roi': 'Average client ROI',
    'results.reach': 'People reached',
    'results.conversion': 'Satisfaction rate',
    'testimonials.1':
      '"LUCID transformed our digital presence in less than 3 months. The ROI exceeds all our expectations."',
    'testimonials.2':
      '"An exceptional team of talents, managed with impressive rigor. I recommend without reservation."',
    'testimonials.1.author': 'Jean Dupont',
    'testimonials.1.role': 'CEO, TechFlow',
    'testimonials.2.author': 'Marie Laurent',
    'testimonials.2.role': 'Marketing Director, LuxeStyle',
    'footer.legal': 'Legal Notice',
    'footer.privacy': 'Privacy Policy',
    'back.to.top': 'Back to top',
    'results.title': 'Measurable results.',
    'results.subtitle': "We don't choose likes, we choose sales.",
    'contact.title': "Let's start your project.",
    'contact.reassurance': 'Response within 24h — First audit included free.',
    'contact.name': 'Full name',
    'contact.company': 'Company',
    'contact.type': 'Project type',
    'contact.budget': 'Budget',
    'contact.budget.details': 'Specify your budget',
    'contact.budget.details.placeholder': 'E.g. 750,000 FCFA',
    'contact.message': 'Message (required)',
    'contact.submit': 'Send my request',
    'footer.tagline': 'Powered by Data. Elevated by Talent.',
    'footer.join': 'Freelancer Space',
    'join.title': 'Join the LUCID collective.',
    'join.subtitle': 'No more prospecting. Focus on creating.',
    'join.benefit1': 'Regular missions. Stable income.',
    'join.benefit2': 'Professional structure. Controlled visibility.',
    'join.benefit3': 'Access carefully selected premium projects.',
    'join.cta': 'Submit my application',
    'philosophy.vision.title': 'Our Vision',
    'philosophy.vision.subtitle': 'To make every African SME a digitally performing business.',
    'philosophy.vision.body':
      'We believe that a well-supported small business can compete with any player in its market. Digital is that lever. We are the architect who builds it. In West Africa, talent exists, demand exists, the potential is immense. What is missing is a structure capable of connecting the right strategy, the right creatives, and the right tools — at the right time, for the right budget. LUCID Agency was born to fill this void.',
    'philosophy.mission.title': 'Our Mission',
    'philosophy.mission.subtitle': 'To transform your digital presence into a real growth engine.',
    'philosophy.mission.body1':
      "We don't sell visibility. We build data-driven communication systems, executed by carefully selected talents, and measured by a single criterion: your results.",
    'philosophy.mission.body2':
      'For SMEs and startups, we are your outsourced marketing department — strategic, agile, and accessible.',
    'philosophy.mission.body3':
      'For creative freelancers, we are the structure that values your talent and stabilizes your income.',
    'philosophy.values.title': 'Our Values',
    'philosophy.values.subtitle': 'What guides us every day.',
    'philosophy.values.1.title': '01 — Data First',
    'philosophy.values.1.body':
      'No creation without analysis. Every decision is based on real data, not intuitions.',
    'philosophy.values.2.title': '02 — Talent Excellence',
    'philosophy.values.2.body':
      'We only select creatives who precisely match the project. Quality and relevance, not volume.',
    'philosophy.values.3.title': '03 — Measurable Results',
    'philosophy.values.3.body':
      'Likes or sales — we choose sales. Every action is tracked, analyzed, and optimized for your growth.',
    'philosophy.values.4.title': '04 — Total Transparency',
    'philosophy.values.4.body':
      "You know what is being done, why it's being done, and what it produces. No black box, no surprises.",
    'dashboard.nav.overview': 'Dashboard',
    'dashboard.nav.missions': 'Missions',
    'dashboard.nav.messages': 'Messages',
    'dashboard.nav.settings': 'Settings',
    'dashboard.nav.logout': 'Logout',
    'dashboard.welcome': 'Hello, {{name}} 👋',
    'dashboard.welcome.sub': "Here's what's happening in your space today.",
    'dashboard.stats.activeMissions': 'Active Missions',
    'dashboard.stats.missions': 'Available Missions',
    'dashboard.stats.applications': 'Applications',
    'dashboard.stats.revenue': 'Monthly Revenue',
    'dashboard.stats.profile': 'Profile Completion',
    'dashboard.nav.contracts': 'My Contracts',
    'dashboard.nav.applications': 'My Applications',
    'dashboard.nav.saved': 'Saved',
    'dashboard.settings.security.change': 'Change Password',
    'dashboard.settings.security.current': 'Current Password',
    'dashboard.settings.security.new': 'New Password',
    'dashboard.settings.security.confirm': 'Confirm New Password',
    'dashboard.settings.security.submit': 'Update Password',
    'admin.nav.projects.new': 'New Project',
    'admin.settings.agency.title': 'Agency Info',
    'admin.settings.security.title': 'Security',
    'admin.projects.table.project': 'Project',
    'admin.projects.table.client': 'Client',
    'admin.projects.table.talent': 'Talent',
    'admin.projects.table.budget': 'Budget',
    'admin.projects.table.status': 'Status',
    'admin.projects.status.inprogress': 'In Progress',
    'admin.projects.status.completed': 'Completed',
    'admin.projects.status.onhold': 'On Hold',
    'dashboard.missions.title': 'Recommended Missions',
    'dashboard.missions.search': 'Search missions...',
    'dashboard.missions.view': 'View Offer',
    'dashboard.messages.title': 'Your Conversations',
    'dashboard.messages.empty': 'No messages yet.',
    'dashboard.settings.title': 'Account Settings',
    'dashboard.settings.profile': 'Public Profile',
    'dashboard.settings.notifications': 'Notifications',
    'dashboard.settings.security': 'Security',
    'admin.nav.talents': 'Talent Management',
    'admin.nav.clients': 'Clients',
    'admin.nav.projects': 'Client Projects',
    'admin.nav.messages': 'Messaging',
    'admin.nav.settings': 'Settings',
    'admin.welcome': 'Admin Back-office 🛠️',
    'admin.welcome.sub': 'Manage your talents and client projects with ease.',
    'admin.stats.activeTalents': 'Active Talents',
    'admin.stats.clients': 'Client contacts',
    'admin.stats.activeProjects': 'Active Projects',
    'admin.stats.pendingRequests': 'Pending Requests',
    'admin.talents.title': 'Latest Talent Requests',
    'admin.talents.table.talent': 'Talent',
    'admin.talents.table.specialty': 'Specialty',
    'admin.talents.table.date': 'Date',
    'admin.talents.table.status': 'Status',
    'admin.talents.table.actions': 'Actions',
    'admin.status.approved': 'Approved',
    'admin.status.pending': 'Pending',
    'admin.status.rejected': 'Rejected',
    'login.title.admin': 'Admin Access',
    'login.title.freelancer': 'Freelancer Space',
    'login.subtitle': 'Please log in to access your space.',
    'login.label.username': 'Username',
    'login.label.email': 'Email',
    'login.label.password': 'Password',
    'login.placeholder.username': 'Your username',
    'login.placeholder.password': '••••••••',
    'login.emailPlaceholder': 'your@email.com',
    'login.passwordPlaceholder': '••••••••',
    'login.button': 'Log In',
    'login.button.admin': 'Access admin',
    'login.error': 'Incorrect credentials. Please try again.',
    'login.error.missingFields': 'Please enter your email and password.',
    'login.error.invalidEmail': 'Please enter a valid email address.',
    'login.error.rateLimit': 'Too many attempts. Try again in {{seconds}} seconds.',
    'login.error.adminAccess': 'This account cannot access the admin area.',
    'login.error.noFreelancer': 'No freelancer application is linked to this account.',
    'login.error.pending': 'Your application is pending review.',
    'login.error.rejected': 'Your application has been rejected.',
    'login.error.suspended': 'Your account is suspended.',
    'login.error.invalidCredentials': 'Incorrect email or password.',
    'login.error.emailNotConfirmed': 'Please confirm your email before logging in.',
    'login.error.profileMissing': 'Incomplete account. Contact an administrator.',
    'login.error.generic': 'An error occurred. Please try again.',
    'login.togglePassword': 'Show or hide password',
    'login.submitLoading': 'Signing in...',
    'login.registerPrompt': "Don't have an account?",
    'login.registerLink': 'Sign up',
    'login.reset.link': 'Forgot password?',
    'login.reset.title': 'Forgot password?',
    'login.reset.subtitle': 'Enter your email and we will send you a reset link.',
    'login.reset.submit': 'Send link',
    'login.reset.submitLoading': 'Sending...',
    'login.reset.back': 'Back to login',
    'login.reset.success.title': 'Email sent!',
    'login.reset.success.body': 'Check your inbox and click the link to reset your password.',
    'login.reset.error.missingEmail': 'Please enter your email.',
    'login.reset.error.invalidEmail': 'Please enter a valid email address.',
    'login.reset.error.sendFailed': 'Unable to send the link. Check the email address.',
    'resetPassword.loading.title': 'Checking your link',
    'resetPassword.loading.body': 'We are preparing your recovery session.',
    'resetPassword.title': 'Reset your password',
    'resetPassword.subtitle':
      'Choose a new password using exactly the same security rules as during signup.',
    'resetPassword.submit': 'Reset password',
    'resetPassword.submitLoading': 'Resetting...',
    'resetPassword.success.title': 'Password updated',
    'resetPassword.success.body':
      'Your password has been reset successfully. Redirecting to login...',
    'resetPassword.invalid.title': 'Invalid or expired link',
    'resetPassword.invalid.cta': 'Back to login',
    'resetPassword.error.invalidLink': 'This reset link is invalid, incomplete, or expired.',
    'resetPassword.error.missingRecoverySession':
      'The recovery session is missing. Please request a new reset link.',
    'resetPassword.error.generic': 'Unable to reset the password right now.',
    'dashboard.nav.history': 'Mission history',
    'dashboard.stats.available': 'Available missions',
    'dashboard.stats.accepted': 'Accepted missions',
    'dashboard.stats.completed': 'Completed missions',
    'dashboard.profile.fallbackName': 'Freelancer',
    'dashboard.overview.details': 'View details',
    'dashboard.overview.summaryTitle': 'Overview',
    'dashboard.overview.summaryBody':
      'Real missions will appear here as soon as the backend provides usable data for your account.',
    'dashboard.missions.emptyTitle': 'No mission available',
    'dashboard.missions.emptyBody':
      'No real mission is available at the moment. Please check back later.',
    'dashboard.history.emptyTitle': 'No history yet',
    'dashboard.history.emptyBody':
      'No accepted or completed missions are currently available on your account.',
    'dashboard.history.action': 'View missions',
    'dashboard.messages.emptyTitle': 'No messages',
    'dashboard.messages.emptyBody':
      'No real messages are available in your workspace at the moment.',
    'dashboard.settings.card.profileDesc': 'Manage the information visible to the agency.',
    'dashboard.settings.card.notificationsDesc': 'Configure your notification preferences.',
    'dashboard.settings.card.securityDesc': 'Update your password.',
    'dashboard.settings.profile.firstName': 'First name',
    'dashboard.settings.profile.lastName': 'Last name',
    'dashboard.settings.profile.phone': 'Phone',
    'dashboard.settings.profile.phonePlaceholder': '+228 XX XX XX XX',
    'dashboard.settings.profile.portfolio': 'Portfolio',
    'dashboard.settings.profile.portfolioPlaceholder': 'https://myportfolio.com',
    'dashboard.settings.profile.bio': 'Bio',
    'dashboard.settings.profile.bioPlaceholder': 'Describe your profile and expertise...',
    'dashboard.settings.profile.save': 'Save',
    'dashboard.settings.profile.saving': 'Saving...',
    'dashboard.settings.profile.success': 'Profile updated.',
    'dashboard.settings.profile.error': 'Unable to update the profile.',
    'dashboard.settings.security.placeholder': 'Min. 8 characters',
    'dashboard.settings.security.confirmPlaceholder': 'Confirm password',
    'dashboard.settings.security.success': 'Password updated.',
    'dashboard.settings.security.saving': 'Updating...',
    'dashboard.settings.security.error': 'Unable to update the password.',
    'dashboard.settings.security.errorMismatch': 'Passwords do not match.',
    'dashboard.settings.security.errorInvalid': 'Invalid password: {{errors}}.',
    'dashboard.settings.notifications.missions': 'New available missions',
    'dashboard.settings.notifications.history': 'Mission history updates',
    'dashboard.settings.notifications.messages': 'Agency messages',
    'dashboard.settings.notifications.newsletter': 'Monthly newsletter',
    'dashboard.settings.notifications.save': 'Save',
    'admin.common.na': 'N/A',
    'admin.error.invalidSession': 'Invalid admin session.',
    'admin.error.loadTalents': 'Unable to load applications.',
    'admin.error.loadContacts': 'Unable to load contacts.',
    'admin.error.updateStatus': 'Unable to update the status.',
    'admin.search.placeholder': 'Search...',
    'admin.filter.all': 'All',
    'admin.filter.pending': 'Pending',
    'admin.filter.validated': 'Validated',
    'admin.filter.rejected': 'Rejected',
    'admin.filter.suspended': 'Suspended',
    'admin.talents.empty.none': 'No applications received yet.',
    'admin.talents.empty.filtered': 'No results.',
    'admin.talents.table.phone': 'Phone',
    'admin.talents.table.dayRate': 'Day rate',
    'admin.talents.table.onboarding': 'Onboarding',
    'admin.onboarding.complete': 'Complete',
    'admin.onboarding.incomplete': 'Incomplete',
    'admin.status.suspended': 'Suspended',
    'admin.clients.title': 'Client contacts',
    'admin.clients.empty.none': 'No contact received yet.',
    'admin.clients.empty.filtered': 'No contact matches your search.',
    'admin.clients.table.name': 'Name',
    'admin.clients.table.company': 'Company',
    'admin.clients.table.email': 'Email',
    'admin.clients.table.phone': 'Phone',
    'admin.clients.table.projectType': 'Project type',
    'admin.clients.table.budget': 'Budget',
    'admin.clients.table.date': 'Date',
    'admin.clients.table.actions': 'Actions',
    'admin.clients.actions.viewDetails': 'View details',
    'admin.clients.modal.title': 'Client details',
    'admin.clients.modal.firstName': 'First name',
    'admin.clients.modal.message': 'Message',
    'admin.clients.modal.status': 'Status',
    'admin.pagination.rowsPerPage': 'Rows per page',
    'admin.pagination.results': 'results',
    'admin.pagination.of': 'of',
    'admin.pagination.page': 'Page',
    'admin.pagination.on': 'of',
    'admin.pagination.previous': 'Previous',
    'admin.pagination.next': 'Next',
    'admin.pagination.noResults': '0 results',
    'admin.projects.emptyTitle': 'No project available',
    'admin.projects.emptyBody': 'No real project data is currently provided by the backend.',
    'admin.messages.title': 'WhatsApp messaging',
    'admin.messages.subtitle': 'Contact your approved talents directly.',
    'admin.messages.empty': 'No approved talent.',
    'admin.messages.openWhatsapp': 'Open WhatsApp',
    'admin.messages.noPhone': 'Phone unavailable',
    'admin.settings.security.label': 'Security',
    'admin.settings.security.desc': 'Password and admin access.',
    'admin.settings.security.newLabel': 'New password',
    'admin.settings.security.newPlaceholder': 'Min. 8 characters',
    'admin.settings.security.confirmLabel': 'Confirm',
    'admin.settings.security.confirmPlaceholder': 'Repeat the password',
    'admin.settings.security.toggleVisibility': 'Show or hide password',
    'admin.settings.security.submit': 'Update',
    'admin.settings.security.saving': 'Updating...',
    'admin.settings.security.success': 'Password updated.',
    'admin.settings.security.error': 'Unable to update the password.',
    'admin.settings.security.errorMismatch': 'Passwords do not match.',
    'admin.settings.security.errorMin': 'Minimum 8 characters.',
    'admin.settings.security.errorInvalid': 'Invalid password: {{errors}}.',
    'admin.settings.system.label': 'System settings',
    'admin.settings.system.desc': 'Summary view of loaded data.',
    'admin.settings.system.totalTalents': 'Registered talents',
    'admin.settings.system.validatedTalents': 'Validated talents',
    'admin.settings.system.pendingTalents': 'Pending',
    'admin.settings.back': 'Back',
    'admin.actions.processing': 'Processing...',
    'admin.actions.approve': 'Approve',
    'admin.actions.reject': 'Reject',
    'admin.reject.reasonLabel': 'Rejection reason',
    'admin.reject.reasonPlaceholder': 'Briefly explain why the application is being rejected.',
    'admin.reject.reasonRequired': 'A rejection reason is required.',
    'admin.reject.confirm': 'Confirm reject',
    'admin.modal.validated': 'Validated',
    'admin.modal.suspended': 'Suspended',
    'admin.modal.rejected': 'Rejected',
    'completeProfile.title': 'Complete your profile',
    'completeProfile.subtitle':
      'To access the dashboard, please provide the following information.',
    'completeProfile.field.phone': 'Phone number',
    'completeProfile.field.phonePlaceholder': '+221770000000',
    'completeProfile.field.rate': 'Daily rate (FCFA)',
    'completeProfile.field.rateSuffix': '/day',
    'completeProfile.field.bio': 'Bio (optional)',
    'completeProfile.field.bioPlaceholder': 'Tell us about yourself and your experience...',
    'completeProfile.field.speciality': 'Specialty (optional)',
    'completeProfile.field.specialityPlaceholder': 'Ex: React developer, Video editor...',
    'completeProfile.submit.idle': 'Complete my profile',
    'completeProfile.submit.loading': 'Saving...',
    'completeProfile.loading.title': 'Loading profile',
    'completeProfile.loading.body': 'We are preparing your freelancer space.',
    'completeProfile.pending.title': 'Preparing your profile',
    'completeProfile.pending.body':
      'Your freelancer information is still loading. Please try again in a moment.',
    'completeProfile.fallback.title': 'Session required',
    'completeProfile.fallback.body': 'Please sign in again to finish onboarding.',
    'completeProfile.success.title': 'Profile completed!',
    'completeProfile.success.body': 'Redirecting to the dashboard...',
    'completeProfile.error.phoneRequired': 'Phone number is required',
    'completeProfile.error.phoneInvalid': 'Invalid format: +COUNTRYCODE followed by 8 to 15 digits',
    'completeProfile.error.rateInvalid': 'Rate must be between 1000 and 1000000 FCFA.',
    'completeProfile.error.noSession': 'Invalid session.',
    'completeProfile.error.submit': 'Unable to complete the profile.',
    'join.specialty.graphisme': 'Graphic designer',
    'join.specialty.video': 'Video editor / Motion designer',
    'join.specialty.redaction': 'Writer / Copywriter',
    'join.specialty.webdev': 'Web developer',
    'join.specialty.photo': 'Photographer',
    'join.specialty.marketing': 'Digital marketing specialist',
    'join.specialty.autre': 'Other expertise',
    'join.success.title': 'Application sent!',
    'join.success.body1': 'Your application has been received.',
    'join.success.body2': 'Our team will review it and get back to you.',
    'join.field.firstName': 'First name',
    'join.field.lastName': 'Last name',
    'join.field.email': 'Email',
    'join.field.phone': 'Phone number',
    'join.field.rate': 'Daily rate (FCFA)',
    'join.field.rateSuffix': '/day',
    'join.field.password': 'Password',
    'join.field.confirmPassword': 'Confirm',
    'join.field.specialty': 'Specialty',
    'join.field.portfolio': 'Portfolio link',
    'join.field.message': 'Message (required)',
    'join.placeholder.firstName': 'Ex: John',
    'join.placeholder.lastName': 'Ex: Doe',
    'join.placeholder.email': 'Ex: john@email.com',
    'join.placeholder.phone': '+221770000000',
    'join.placeholder.password': 'Min. 8 characters',
    'join.placeholder.confirmPassword': 'Repeat your password',
    'join.placeholder.specialty': 'Choose your specialty',
    'join.placeholder.portfolio': 'https://myportfolio.com',
    'join.placeholder.message': 'Tell us about yourself and your experience...',
    'join.help.phone': 'Format: +countrycode followed by 8 to 15 digits',
    'join.help.rate': 'Min: 1000 FCFA | Max: 1,000,000 FCFA',
    'join.password.show': 'Show',
    'join.password.hide': 'Hide',
    'join.submit.loading': 'Sending...',
    'join.loginPrompt': 'Already have an account?',
    'join.loginLink': 'Log in',
    'join.legal.prefix': 'I accept the',
    'join.legal.link': 'Terms of use',
    'join.legal.error': 'You must accept the terms of use.',
    'join.error.generic': 'An error occurred. Please try again.',
    'join.error.emailInUse': 'This email is already in use.',
    'join.error.rateLimit': 'Too many attempts. Try again in {{minutes}} minutes.',
    'validation.min2': 'Minimum 2 characters',
    'validation.max50': 'Maximum 50 characters',
    'validation.invalidCharacters': 'Invalid characters',
    'validation.invalidEmail': 'Invalid email',
    'validation.passwordMin': 'Minimum 8 characters',
    'validation.passwordUppercase': 'At least one uppercase letter',
    'validation.passwordDigit': 'At least one digit',
    'validation.passwordSpecial': 'At least one special character',
    'validation.phoneRequired': 'Phone number is required',
    'validation.phoneFormat': 'Format: +COUNTRYCODE followed by 8 to 15 digits',
    'validation.rateMin': 'Minimum 1000 FCFA',
    'validation.rateMax': 'Maximum 1000000 FCFA',
    'validation.specialtyRequired': 'Please choose a specialty',
    'validation.specialtyInvalid': 'Invalid specialty',
    'validation.invalidUrl': 'Invalid URL (ex: https://myportfolio.com)',
    'validation.max1000': 'Maximum 1000 characters',
    'validation.noHtml': 'HTML is not allowed',
    'validation.passwordMismatch': 'Passwords do not match',
    'login.back': 'Back to home',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.menu': 'Menu',
    'common.sessionCheck': 'Checking session...',
    'common.redirecting': 'Redirecting...',
    'common.clickToReveal': 'Click to reveal...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// ✅ Validation stricte — seules FR et EN sont acceptées
function isSafeLang(value: string | null): value is Language {
  return value === 'FR' || value === 'EN';
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>('FR');

  useEffect(() => {
    try {
      // ✅ localStorage OK pour préférence de langue (donnée non sensible)
      // ✅ Valeur strictement validée avant usage — évite toute pollution
      const saved = localStorage.getItem('lucid_lang');
      if (isSafeLang(saved)) {
        setLangState(saved);
        document.documentElement.lang = saved.toLowerCase();
      }
    } catch {
      // Si localStorage bloqué, on reste sur FR par défaut
    }
  }, []);

  const setLang = (newLang: Language) => {
    // ✅ Double vérification au runtime
    if (!isSafeLang(newLang)) return;
    setLangState(newLang);
    try {
      localStorage.setItem('lucid_lang', newLang);
    } catch {
      // Silencieux
    }
    document.documentElement.lang = newLang.toLowerCase();
  };

  // ✅ Fonction t() — retourne la clé brute si traduction manquante (jamais undefined)
  const t = (key: string): string => {
    return translations[lang][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
