import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'FR' | 'EN';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  FR: {
    'nav.method': 'Méthode',
    'nav.philosophy': 'Philosophie',
    'nav.talents': 'Talents',
    'nav.offers': 'Offres',
    'nav.contact': 'Contact',
    'nav.cta': 'Démarrer un projet',
    'hero.title1': 'Marketing Digital :',
    'hero.title2': "Passez de l'ombre à la lumière.",
    'hero.subtitle':
      "L'agence qui combine l'agilité des meilleurs créatifs freelances à la rigueur d'une stratégie Data-Driven.",
    'hero.cta.primary': 'Démarrer un projet',
    'hero.cta.secondary': 'Voir nos talents',
    'vision.title': 'Soyez LUCID sur votre stratégie.',
    'vision.body':
      "Le marché est bruyant. Pour vous faire entendre, vous n'avez pas besoin de crier plus fort — vous avez besoin de voir plus clair. Chez LUCID, nous ne vendons pas du 'joli', nous vendons du rentable. Nous analysons vos données pour piloter nos experts créatifs.",
    'vision.stat1.val': '3x',
    'vision.stat1.label': 'ROI moyen constaté',
    'vision.stat2.val': '48h',
    'vision.stat2.label': 'Délai de démarrage',
    'vision.stat3.val': '100%',
    'vision.stat3.label': 'Projets livrés clé en main',
    'method.title': 'Notre Méthode',
    'method.step1.title': 'ANALYSE',
    'method.step1.body': 'Nous auditons votre marché et vos chiffres avant de bouger.',
    'method.step2.title': 'CASTING',
    'method.step2.body': "Nous sélectionnons dans notre réseau l'expert parfait pour VOTRE besoin.",
    'method.step3.title': 'PILOTAGE',
    'method.step3.body': 'Nous gérons la production de A à Z. Vous recevez un projet clé en main.',
    'talents.title': "L'élite des créatifs. Pilotée par nos experts.",
    'talents.cta': "Réserver ce talent via l'Agence",
    'talents.filter.all': 'Tous',
    'talents.filter.branding': 'Branding',
    'talents.filter.video': 'Vidéo',
    'talents.filter.web': 'Web',
    'talents.filter.photo': 'Photo',
    'talents.more': 'Voir plus',
    'offers.title': 'Nos Solutions sur Mesure',
    'offers.included': "Inclus dans l'offre",
    'offers.audit.name': 'DIAGNOSTIC',
    'offers.audit.type': 'Audit Stratégique',
    'offers.audit.features':
      'Audit de visibilité · Analyse de la concurrence · Roadmap stratégique',
    'offers.audit.included': 'Présentation détaillée & Recommandations',
    'offers.audit.cta': 'Réserver mon audit',
    'offers.production.name': 'SOLUTIONS',
    'offers.production.type': 'Production Créative',
    'offers.production.features':
      'Identité visuelle · Développement Web · Contenus Social Media · Publicité (Ads)',
    'offers.production.included': 'Casting experts + Pilotage de projet',
    'offers.production.cta': 'Lancer une production',
    'offers.growth.name': 'PARTENAIRE',
    'offers.growth.type': 'Accompagnement Croissance',
    'offers.growth.features':
      'Pilotage Data-Driven · Création continue · Optimisation du ROI · Support prioritaire',
    'offers.growth.included': 'Accès direct aux experts + Reporting Live',
    'offers.growth.badge': 'Le plus populaire',
    'offers.growth.cta': 'Devenir partenaire',
    'results.title': 'Des résultats mesurables.',
    'results.subtitle': 'Nous ne choisissons pas les likes, nous choisissons les ventes.',
    'contact.title': 'Démarrons votre projet.',
    'contact.reassurance': 'Réponse sous 24h — Premier audit offert.',
    'contact.name': 'Nom complet',
    'contact.company': 'Entreprise',
    'contact.type': 'Type de projet',
    'contact.budget': 'Budget',
    'contact.message': 'Message (facultatif)',
    'contact.submit': 'Envoyer ma demande',
    'footer.tagline': 'Propulsé par la Data. Sublimé par le Talent.',
    'footer.join': 'Espace Freelances',
    'join.title': 'Rejoindre le collectif LUCID.',
    'join.subtitle': 'Fini la prospection. Concentrez-vous sur la création.',
    'join.benefit1': 'Missions régulières. Revenus stables.',
    'join.benefit2': 'Structure professionnelle. Visibilité maîtrisée.',
    'join.benefit3': 'Accédez à des projets premium sélectionnés.',
    'join.cta': 'Soumettre ma candidature',
    'philosophy.vision.title': 'Notre Vision',
    'philosophy.vision.subtitle':
      'Faire de chaque PME africaine une entreprise qui performe digitalement.',
    'philosophy.vision.body':
      'Nous croyons qu’une petite entreprise bien accompagnée peut rivaliser avec n’importe quel acteur de son marché. Le digital est ce levier. Nous sommes l’architecte qui le construit. En Afrique de l’Ouest, le talent existe, la demande existe, le potentiel est immense. Ce qui manque, c’est une structure capable de relier la bonne stratégie, les bons créatifs et les bons outils — au bon moment, pour le bon budget. LUCID Agency est née pour combler ce vide.',
    'philosophy.mission.title': 'Notre Mission',
    'philosophy.mission.subtitle':
      'Transformer votre présence digitale en moteur de croissance réelle.',
    'philosophy.mission.body1':
      'Nous ne vendons pas de la visibilité. Nous construisons des systèmes de communication pilotés par la donnée, exécutés par des talents soigneusement sélectionnés, et mesurés à l’aune d’un seul critère : vos résultats.',
    'philosophy.mission.body2':
      'Pour les PME et startups, nous sommes votre département marketing externalisé — stratégique, agile, et accessible.',
    'philosophy.mission.body3':
      'Pour les freelances créatifs, nous sommes la structure qui valorise votre talent et stabilise vos revenus.',
    'philosophy.values.title': 'Nos Valeurs',
    'philosophy.values.subtitle': 'Ce qui nous guide chaque jour.',
    'philosophy.values.1.title': '01 — La donnée avant tout',
    'philosophy.values.1.body':
      'Aucune création sans analyse. Chaque décision est fondée sur des données réelles, pas sur des intuitions.',
    'philosophy.values.2.title': '02 — L’excellence des talents',
    'philosophy.values.2.body':
      'Nous sélectionnons uniquement les créatifs qui correspondent précisément au projet. Qualité et pertinence, pas volume.',
    'philosophy.values.3.title': '03 — Des résultats mesurables',
    'philosophy.values.3.body':
      'Likes ou ventes — nous choisissons les ventes. Chaque action est tracée, analysée et optimisée pour votre croissance.',
    'philosophy.values.4.title': '04 — La transparence totale',
    'philosophy.values.4.body':
      'Vous savez ce qui est fait, pourquoi c’est fait, et ce que ça produit. Aucune boîte noire, aucune surprise.',
    'dashboard.nav.overview': 'Tableau de bord',
    'dashboard.nav.missions': 'Missions',
    'dashboard.nav.messages': 'Messages',
    'dashboard.nav.settings': 'Paramètres',
    'dashboard.nav.logout': 'Déconnexion',
    'dashboard.welcome': 'Bonjour, {{name}} 👋',
    'dashboard.welcome.sub': "Voici ce qui se passe sur votre espace aujourd'hui.",
    'dashboard.stats.activeMissions': 'Missions en cours',
    'dashboard.stats.missions': 'Missions disponibles',
    'dashboard.stats.applications': 'Candidatures',
    'dashboard.stats.revenue': 'Revenus ce mois',
    'dashboard.stats.profile': 'Profil complété',
    'dashboard.nav.contracts': 'Mes Contrats',
    'dashboard.nav.applications': 'Mes Candidatures',
    'dashboard.nav.saved': 'Enregistrés',
    'dashboard.settings.security.change': 'Changer le mot de passe',
    'dashboard.settings.security.current': 'Mot de passe actuel',
    'dashboard.settings.security.new': 'Nouveau mot de passe',
    'dashboard.settings.security.confirm': 'Confirmer le nouveau mot de passe',
    'dashboard.settings.security.submit': 'Mettre à jour le mot de passe',
    'admin.nav.projects.new': 'Nouveau Projet',
    'admin.settings.agency.title': 'Infos Agence',
    'admin.settings.security.title': 'Sécurité',
    'admin.projects.table.project': 'Projet',
    'admin.projects.table.client': 'Client',
    'admin.projects.table.talent': 'Talent',
    'admin.projects.table.budget': 'Budget',
    'admin.projects.table.status': 'Statut',
    'admin.projects.status.inprogress': 'En cours',
    'admin.projects.status.completed': 'Terminé',
    'admin.projects.status.onhold': 'En pause',
    'dashboard.missions.title': 'Missions recommandées',
    'dashboard.missions.search': 'Rechercher une mission...',
    'dashboard.missions.view': "Voir l'offre",
    'dashboard.messages.title': 'Vos conversations',
    'dashboard.messages.empty': 'Aucun message pour le moment.',
    'dashboard.settings.title': 'Paramètres du compte',
    'dashboard.settings.profile': 'Profil Public',
    'dashboard.settings.notifications': 'Notifications',
    'dashboard.settings.security': 'Sécurité',
    'admin.nav.talents': 'Gestion Talents',
    'admin.nav.projects': 'Projets Clients',
    'admin.nav.messages': 'Messagerie',
    'admin.nav.settings': 'Paramètres',
    'admin.welcome': 'Back-office Admin 🛠️',
    'admin.welcome.sub': 'Gérez vos talents et vos projets clients en toute simplicité.',
    'admin.stats.activeTalents': 'Talents Actifs',
    'admin.stats.activeProjects': 'Projets en cours',
    'admin.stats.pendingRequests': 'Demandes en attente',
    'admin.talents.title': 'Dernières demandes de talents',
    'admin.talents.table.talent': 'Talent',
    'admin.talents.table.specialty': 'Spécialité',
    'admin.talents.table.date': 'Date',
    'admin.talents.table.status': 'Statut',
    'admin.talents.table.actions': 'Actions',
    'admin.status.approved': 'Approuvé',
    'admin.status.pending': 'En attente',
    'admin.status.rejected': 'Refusé',
    'login.title.admin': 'Accès Admin',
    'login.title.freelancer': 'Espace Freelance',
    'login.subtitle': 'Veuillez vous connecter pour accéder à votre espace.',
    'login.label.username': 'Pseudo',
    'login.label.password': 'Mot de passe',
    'login.placeholder.username': 'Votre pseudo',
    'login.placeholder.password': '••••••••',
    'login.button': 'Se connecter',
    'login.error': 'Identifiants incorrects. Veuillez réessayer.',
    'login.back': "Retour à l'accueil",
    'common.clickToReveal': 'Cliquez pour découvrir...',
  },
  EN: {
    'nav.method': 'Method',
    'nav.philosophy': 'Philosophy',
    'nav.talents': 'Talents',
    'nav.offers': 'Offers',
    'nav.contact': 'Contact',
    'nav.cta': 'Start a project',
    'hero.title1': 'Digital Marketing:',
    'hero.title2': 'Step out of the shadows.',
    'hero.subtitle':
      'The agency that combines the agility of top freelance creatives with the rigor of a Data-Driven strategy.',
    'hero.cta.primary': 'Start a project',
    'hero.cta.secondary': 'Meet our talents',
    'vision.title': 'Be LUCID about your strategy.',
    'vision.body':
      "The market is noisy. To be heard, you don't need to shout louder — you need to see clearer. At LUCID, we don't sell 'pretty', we sell profitable. We analyze your data to drive our creative experts.",
    'vision.stat1.val': '3x',
    'vision.stat1.label': 'Average measured ROI',
    'vision.stat2.val': '48h',
    'vision.stat2.label': 'Time to launch',
    'vision.stat3.val': '100%',
    'vision.stat3.label': 'Projects delivered end-to-end',
    'method.title': 'Our Method',
    'method.step1.title': 'ANALYSIS',
    'method.step1.body': 'We audit your market and numbers before making any move.',
    'method.step2.title': 'CASTING',
    'method.step2.body': 'We select from our network the perfect expert for YOUR need.',
    'method.step3.title': 'MANAGEMENT',
    'method.step3.body': 'We handle production from A to Z. You receive a ready-to-use project.',
    'talents.title': 'The creative elite. Driven by our experts.',
    'talents.cta': 'Book this talent via the Agency',
    'talents.filter.all': 'All',
    'talents.filter.branding': 'Branding',
    'talents.filter.video': 'Video',
    'talents.filter.web': 'Web',
    'talents.filter.photo': 'Photo',
    'talents.more': 'View more',
    'offers.title': 'Tailored Solutions',
    'offers.included': 'Included in the offer',
    'offers.audit.name': 'DIAGNOSIS',
    'offers.audit.type': 'Strategic Audit',
    'offers.audit.features': 'Visibility audit · Competitor analysis · Strategic roadmap',
    'offers.audit.included': 'Detailed presentation & Recommendations',
    'offers.audit.cta': 'Book my audit',
    'offers.production.name': 'SOLUTIONS',
    'offers.production.type': 'Creative Production',
    'offers.production.features':
      'Visual identity · Web development · Social Media content · Advertising (Ads)',
    'offers.production.included': 'Expert casting + Project management',
    'offers.production.cta': 'Start a production',
    'offers.growth.name': 'PARTNER',
    'offers.growth.type': 'Growth Partnership',
    'offers.growth.features':
      'Data-Driven steering · Continuous creation · ROI optimization · Priority support',
    'offers.growth.included': 'Direct expert access + Live reporting',
    'offers.growth.badge': 'Most popular',
    'offers.growth.cta': 'Become a partner',
    'results.title': 'Measurable results.',
    'results.subtitle': "We don't choose likes, we choose sales.",
    'contact.title': "Let's start your project.",
    'contact.reassurance': 'Response within 24h — First audit included free.',
    'contact.name': 'Full name',
    'contact.company': 'Company',
    'contact.type': 'Project type',
    'contact.budget': 'Budget',
    'contact.message': 'Message (optional)',
    'contact.submit': 'Send my request',
    'footer.tagline': 'Powered by Data. Elevated by Talent.',
    'footer.join': 'Freelancer Space',
    'join.title': 'Join the LUCID collective.',
    'join.subtitle': 'No more prospecting. Focus on creating.',
    'join.benefit1': 'Regular missions. Stable income.',
    'join.benefit2': 'Professional structure. Controlled visibility.',
    'join.benefit3': 'Access carefully selected premium projects.',
    'join.cta': 'Submit my application',
    'philosophy.vision.title': 'Our Vision',
    'philosophy.vision.subtitle': 'To make every African SME a digitally performing business.',
    'philosophy.vision.body':
      'We believe that a well-supported small business can compete with any player in its market. Digital is that lever. We are the architect who builds it. In West Africa, talent exists, demand exists, the potential is immense. What is missing is a structure capable of connecting the right strategy, the right creatives, and the right tools — at the right time, for the right budget. LUCID Agency was born to fill this void.',
    'philosophy.mission.title': 'Our Mission',
    'philosophy.mission.subtitle': 'To transform your digital presence into a real growth engine.',
    'philosophy.mission.body1':
      "We don't sell visibility. We build data-driven communication systems, executed by carefully selected talents, and measured by a single criterion: your results.",
    'philosophy.mission.body2':
      'For SMEs and startups, we are your outsourced marketing department — strategic, agile, and accessible.',
    'philosophy.mission.body3':
      'For creative freelancers, we are the structure that values your talent and stabilizes your income.',
    'philosophy.values.title': 'Our Values',
    'philosophy.values.subtitle': 'What guides us every day.',
    'philosophy.values.1.title': '01 — Data First',
    'philosophy.values.1.body':
      'No creation without analysis. Every decision is based on real data, not intuitions.',
    'philosophy.values.2.title': '02 — Talent Excellence',
    'philosophy.values.2.body':
      'We only select creatives who precisely match the project. Quality and relevance, not volume.',
    'philosophy.values.3.title': '03 — Measurable Results',
    'philosophy.values.3.body':
      'Likes or sales — we choose sales. Every action is tracked, analyzed, and optimized for your growth.',
    'philosophy.values.4.title': '04 — Total Transparency',
    'philosophy.values.4.body':
      "You know what is being done, why it's being done, and what it produces. No black box, no surprises.",
    'dashboard.nav.overview': 'Dashboard',
    'dashboard.nav.missions': 'Missions',
    'dashboard.nav.messages': 'Messages',
    'dashboard.nav.settings': 'Settings',
    'dashboard.nav.logout': 'Logout',
    'dashboard.welcome': 'Hello, {{name}} 👋',
    'dashboard.welcome.sub': "Here's what's happening in your space today.",
    'dashboard.stats.activeMissions': 'Active Missions',
    'dashboard.stats.missions': 'Available Missions',
    'dashboard.stats.applications': 'Applications',
    'dashboard.stats.revenue': 'Monthly Revenue',
    'dashboard.stats.profile': 'Profile Completion',
    'dashboard.nav.contracts': 'My Contracts',
    'dashboard.nav.applications': 'My Applications',
    'dashboard.nav.saved': 'Saved',
    'dashboard.settings.security.change': 'Change Password',
    'dashboard.settings.security.current': 'Current Password',
    'dashboard.settings.security.new': 'New Password',
    'dashboard.settings.security.confirm': 'Confirm New Password',
    'dashboard.settings.security.submit': 'Update Password',
    'admin.nav.projects.new': 'New Project',
    'admin.settings.agency.title': 'Agency Info',
    'admin.settings.security.title': 'Security',
    'admin.projects.table.project': 'Project',
    'admin.projects.table.client': 'Client',
    'admin.projects.table.talent': 'Talent',
    'admin.projects.table.budget': 'Budget',
    'admin.projects.table.status': 'Status',
    'admin.projects.status.inprogress': 'In Progress',
    'admin.projects.status.completed': 'Completed',
    'admin.projects.status.onhold': 'On Hold',
    'dashboard.missions.title': 'Recommended Missions',
    'dashboard.missions.search': 'Search missions...',
    'dashboard.missions.view': 'View Offer',
    'dashboard.messages.title': 'Your Conversations',
    'dashboard.messages.empty': 'No messages yet.',
    'dashboard.settings.title': 'Account Settings',
    'dashboard.settings.profile': 'Public Profile',
    'dashboard.settings.notifications': 'Notifications',
    'dashboard.settings.security': 'Security',
    'admin.nav.talents': 'Talent Management',
    'admin.nav.projects': 'Client Projects',
    'admin.nav.messages': 'Messaging',
    'admin.nav.settings': 'Settings',
    'admin.welcome': 'Admin Back-office 🛠️',
    'admin.welcome.sub': 'Manage your talents and client projects with ease.',
    'admin.stats.activeTalents': 'Active Talents',
    'admin.stats.activeProjects': 'Active Projects',
    'admin.stats.pendingRequests': 'Pending Requests',
    'admin.talents.title': 'Latest Talent Requests',
    'admin.talents.table.talent': 'Talent',
    'admin.talents.table.specialty': 'Specialty',
    'admin.talents.table.date': 'Date',
    'admin.talents.table.status': 'Status',
    'admin.talents.table.actions': 'Actions',
    'admin.status.approved': 'Approved',
    'admin.status.pending': 'Pending',
    'admin.status.rejected': 'Rejected',
    'login.title.admin': 'Admin Access',
    'login.title.freelancer': 'Freelancer Space',
    'login.subtitle': 'Please log in to access your space.',
    'login.label.username': 'Username',
    'login.label.password': 'Password',
    'login.placeholder.username': 'Your username',
    'login.placeholder.password': '••••••••',
    'login.button': 'Log In',
    'login.error': 'Incorrect credentials. Please try again.',
    'login.back': 'Back to home',
    'common.clickToReveal': 'Click to reveal...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>('FR');

  useEffect(() => {
    const saved = localStorage.getItem('lucid_lang') as Language;
    if (saved && (saved === 'FR' || saved === 'EN')) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('lucid_lang', newLang);
    document.documentElement.lang = newLang.toLowerCase();
  };

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
